class Article {
  final String text;
  final String domain;
  final String by;
  final String age;
  final int score;
  final int commentsCount;

  const Article({
    this.text,
    this.domain,
    this.by,
    this.age,
    this.score,
    this.commentsCount,
  });
}

final articles = [
  Article(
    text:
        'Circular Shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'BMW says electric car mass production not viable until 2020',
    domain: 'reuters.com',
    by: 'Mononokay',
    age: '2 hours',
    score: 81,
    commentsCount: 128,
  ),
  Article(
    text: 'Evolution is the new deep learning',
    domain: 'sentient.ai',
    by: 'jonbaer',
    age: '4 hours',
    score: 200,
    commentsCount: 87,
  ),
  Article(
    text: 'TCP tracepoints have arrived in Linux',
    domain: 'brendangregg.com',
    by: 'brendangregg',
    age: '1 hours',
    score: 35,
    commentsCount: 0,
  ),
  Article(
    text:
        'Section 230: a key legal shield for facebook, google is about to change',
    domain: 'npr.org',
    by: 'Mononokay',
    age: '5 hours',
    score: 156,
    commentsCount: 66,
  ),
  Article(
    text: 'A visiting star jostled our solar system 70,000 years ago',
    domain: 'gizmodo.com',
    by: 'rbanffy',
    age: '7 hours',
    score: 175,
    commentsCount: 60,
  ),
  Article(
    text:
        'Circular Shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'BMW says electric car mass production not viable until 2020',
    domain: 'reuters.com',
    by: 'Mononokay',
    age: '2 hours',
    score: 81,
    commentsCount: 128,
  ),
  Article(
    text: 'Evolution is the new deep learning',
    domain: 'sentient.ai',
    by: 'jonbaer',
    age: '4 hours',
    score: 200,
    commentsCount: 87,
  ),
  Article(
    text: 'TCP tracepoints have arrived in Linux',
    domain: 'brendangregg.com',
    by: 'brendangregg',
    age: '1 hours',
    score: 35,
    commentsCount: 0,
  ),
  Article(
    text:
        'Section 230: a key legal shield for facebook, google is about to change',
    domain: 'npr.org',
    by: 'Mononokay',
    age: '5 hours',
    score: 156,
    commentsCount: 66,
  ),
  Article(
    text: 'A visiting star jostled our solar system 70,000 years ago',
    domain: 'gizmodo.com',
    by: 'rbanffy',
    age: '7 hours',
    score: 175,
    commentsCount: 60,
  ),
  Article(
    text:
        'Circular Shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'BMW says electric car mass production not viable until 2020',
    domain: 'reuters.com',
    by: 'Mononokay',
    age: '2 hours',
    score: 81,
    commentsCount: 128,
  ),
  Article(
    text: 'Evolution is the new deep learning',
    domain: 'sentient.ai',
    by: 'jonbaer',
    age: '4 hours',
    score: 200,
    commentsCount: 87,
  ),
  Article(
    text: 'TCP tracepoints have arrived in Linux',
    domain: 'brendangregg.com',
    by: 'brendangregg',
    age: '1 hours',
    score: 35,
    commentsCount: 0,
  ),
  Article(
    text:
        'Section 230: a key legal shield for facebook, google is about to change',
    domain: 'npr.org',
    by: 'Mononokay',
    age: '5 hours',
    score: 156,
    commentsCount: 66,
  ),
  Article(
    text: 'A visiting star jostled our solar system 70,000 years ago',
    domain: 'gizmodo.com',
    by: 'rbanffy',
    age: '7 hours',
    score: 175,
    commentsCount: 60,
  ),
  Article(
    text:
        'Circular Shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'BMW says electric car mass production not viable until 2020',
    domain: 'reuters.com',
    by: 'Mononokay',
    age: '2 hours',
    score: 81,
    commentsCount: 128,
  ),
  Article(
    text: 'Evolution is the new deep learning',
    domain: 'sentient.ai',
    by: 'jonbaer',
    age: '4 hours',
    score: 200,
    commentsCount: 87,
  ),
  Article(
    text: 'TCP tracepoints have arrived in Linux',
    domain: 'brendangregg.com',
    by: 'brendangregg',
    age: '1 hours',
    score: 35,
    commentsCount: 0,
  ),
  Article(
    text:
        'Section 230: a key legal shield for facebook, google is about to change',
    domain: 'npr.org',
    by: 'Mononokay',
    age: '5 hours',
    score: 156,
    commentsCount: 66,
  ),
  Article(
    text: 'A visiting star jostled our solar system 70,000 years ago',
    domain: 'gizmodo.com',
    by: 'rbanffy',
    age: '7 hours',
    score: 175,
    commentsCount: 60,
  ),
  Article(
    text:
        'Circular Shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'BMW says electric car mass production not viable until 2020',
    domain: 'reuters.com',
    by: 'Mononokay',
    age: '2 hours',
    score: 81,
    commentsCount: 128,
  ),
  Article(
    text: 'Evolution is the new deep learning',
    domain: 'sentient.ai',
    by: 'jonbaer',
    age: '4 hours',
    score: 200,
    commentsCount: 87,
  ),
  Article(
    text: 'TCP tracepoints have arrived in Linux',
    domain: 'brendangregg.com',
    by: 'brendangregg',
    age: '1 hours',
    score: 35,
    commentsCount: 0,
  ),
  Article(
    text:
        'Section 230: a key legal shield for facebook, google is about to change',
    domain: 'npr.org',
    by: 'Mononokay',
    age: '5 hours',
    score: 156,
    commentsCount: 66,
  ),
  Article(
    text: 'A visiting star jostled our solar system 70,000 years ago',
    domain: 'gizmodo.com',
    by: 'rbanffy',
    age: '7 hours',
    score: 175,
    commentsCount: 60,
  ),
  Article(
    text:
        'Circular Shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 177,
    commentsCount: 62,
  ),
  Article(
    text: 'BMW says electric car mass production not viable until 2020',
    domain: 'reuters.com',
    by: 'Mononokay',
    age: '2 hours',
    score: 81,
    commentsCount: 128,
  ),
  Article(
    text: 'Evolution is the new deep learning',
    domain: 'sentient.ai',
    by: 'jonbaer',
    age: '4 hours',
    score: 200,
    commentsCount: 87,
  ),
  Article(
    text: 'TCP tracepoints have arrived in Linux',
    domain: 'brendangregg.com',
    by: 'brendangregg',
    age: '1 hours',
    score: 35,
    commentsCount: 0,
  ),
  Article(
    text:
        'Section 230: a key legal shield for facebook, google is about to change',
    domain: 'npr.org',
    by: 'Mononokay',
    age: '5 hours',
    score: 156,
    commentsCount: 66,
  ),
  Article(
    text: 'A visiting star jostled our solar system 70,000 years ago',
    domain: 'gizmodo.com',
    by: 'rbanffy',
    age: '7 hours',
    score: 175,
    commentsCount: 60,
  ),
];
